stop:
  words:
    - "и"
    - "в"
    - "во"
    - "на"
    - "над"
    - "под"
    - "чем"
    - "хотя"
    - "с"
    - "по"
    - "за"
    - "и"
    - "их"
    - "для"
    - "как"
    - "но"
    - "а"
    - "же"
    - "то"
    - "что"
    - "не"
    - "о"
    - "у"
    - "and"
    - "or"
    - "the"
    - "a"
    - "an"
    - "of"
    - "in"
    - "on"
    - "at"
    - "with"
    - "for"
    - "to"
    - "by"
    - "from"
    - "about"
    - "as"
    - "that"
    - "which"
    - "who"
    - "whom"
